### ISSUE TITLE
Hello Enrico !

### ISSUE THREAD

**Issue by lchop** [socrob/mbot_darknet_ros_py#1]
Hello It is Louis! The french guy that works with you in socrob team 2 years ago. How are you ? 
I am on a new project where I want to use YOLO. Would it be possible to use this package ? I manage to make it work. Super nice !

**Comment by lchop** [comment]
It is me again. I manage to make it work.

**Comment by Enri2077** [comment]
Hi Louis! Of course you can use it!
If you are using a 3D sensor like kinect you can also check the localisation node from GitLab: http://dante.isr.tecnico.ulisboa.pt/socrob_at_home/isr_monarch_robot/-/tree/kinetic/mbot_perception/mbot_object_localization
I think you still have access to those repos.

It's also on GitHub, but I don't remember if it is up to date.

**Comment by Enri2077** [comment]
If you need help getting in GitLab you can ask @rui-bettencourt

**Comment by lchop** [comment]
Thanks I used the package on github ! I have an issue where the detection are correct but the bounding box are not correctly positionned, there is always an offset I don't know where does that come from.
